function buildMarkdownReport({ response, taskType, code, language }) {
  const date = new Date().toISOString().split('T')[0];
  return `# AI Code Review Report
**Date:** ${date}  
**Mode:** ${taskType}  
**Language:** ${language}

---

## Explanation
${response.explanation}

## Fix / Issues
${response.fix}

## Best Practices
${response.bestPractices}

## Complexity Analysis
${response.complexity}

---

## Original Code
\`\`\`${language}
${code}
\`\`\`

## Improved Code
\`\`\`${language}
${response.improvedCode}
\`\`\`

---
*Generated by AI Code Review Platform*
`;
}

export function downloadMarkdown({ response, taskType, code, language }) {
  const content = buildMarkdownReport({ response, taskType, code, language });
  const blob = new Blob([content], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `code-review-${taskType}-${Date.now()}.md`;
  a.click();
  URL.revokeObjectURL(url);
}

export function downloadPDF({ response, taskType, code, language }) {
  const html = `<!DOCTYPE html>
<html><head><meta charset="utf-8"><title>Code Review Report</title>
<style>
  body { font-family: system-ui, sans-serif; max-width: 800px; margin: 40px auto; padding: 0 20px; color: #111; }
  h1 { font-size: 1.5rem; border-bottom: 2px solid #6366f1; padding-bottom: 8px; }
  h2 { font-size: 1.1rem; color: #6366f1; margin-top: 24px; }
  pre { background: #f4f4f5; padding: 16px; border-radius: 8px; overflow-x: auto; font-size: 12px; }
  .meta { color: #666; font-size: 14px; margin-bottom: 24px; }
  p { line-height: 1.6; white-space: pre-wrap; }
</style></head><body>
<h1>AI Code Review Report</h1>
<div class="meta"><strong>Mode:</strong> ${taskType} &nbsp;|&nbsp; <strong>Language:</strong> ${language} &nbsp;|&nbsp; <strong>Date:</strong> ${new Date().toLocaleDateString()}</div>
<h2>Explanation</h2><p>${response.explanation}</p>
<h2>Fix / Issues</h2><p>${response.fix}</p>
<h2>Best Practices</h2><p>${response.bestPractices}</p>
<h2>Complexity</h2><p>${response.complexity}</p>
<h2>Original Code</h2><pre>${code.replace(/</g, '&lt;')}</pre>
<h2>Improved Code</h2><pre>${response.improvedCode.replace(/</g, '&lt;')}</pre>
</body></html>`;

  const win = window.open('', '_blank');
  win.document.write(html);
  win.document.close();
  win.onload = () => win.print();
}
